"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Center = { id: string; code: string; name: string; is_active: boolean };
type Person = { id: string; full_name: string; is_active: boolean };
type Customer = { id: string; legal_name: string; trade_name: string | null };
type Assignment = { id: string; person_id: string; cost_center_id: string; allocation_percentage: number; effective_from: string };
type CustomerLink = { id: string; cost_center_id: string; counterparty_id: string; allocation_percentage: number; effective_from: string };
type IssuedDocument = { id: string; document_number: string | null; issue_date: string | null; document_type: string | null; client_name: string | null; total_amount: number | string | null; cost_center_id: string | null };
type ReceivedDocument = { id: string; document_number: string | null; issue_date: string; document_type: string; supplier_name: string; total_amount: number | string; cost_center_id: string | null };
type Payload = { centers: Center[]; people: Person[]; customers: Customer[]; assignments: Assignment[]; customerLinks: CustomerLink[]; issuedDocuments: IssuedDocument[]; receivedDocuments: ReceivedDocument[] };

const today = () => new Date().toISOString().slice(0, 10);
const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });

export function CostCenterManagement({ organizationId }: { organizationId: string | null }) {
  const [data, setData] = useState<Payload | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [expandedGroups, setExpandedGroups] = useState<string[]>([]);
  const [centerSort, setCenterSort] = useState<{ key: "center" | "people" | "customers" | "movements"; direction: "asc" | "desc" }>({ key: "center", direction: "asc" });
  const [selectedCenter, setSelectedCenter] = useState<Center | null>(null);
  const [issuedId, setIssuedId] = useState(""); const [receivedId, setReceivedId] = useState(""); const [modalPersonId, setModalPersonId] = useState(""); const [modalAllocation, setModalAllocation] = useState("100"); const [modalDate, setModalDate] = useState(today());
  const [centerCode, setCenterCode] = useState(""); const [centerName, setCenterName] = useState("");

  const load = useCallback(async () => {
    if (!organizationId) return;
    const response = await fetch(`/api/cost-centers?organizationId=${encodeURIComponent(organizationId)}`, { cache: "no-store" });
    if (!response.ok) return setMessage("No fue posible cargar los centros de costo.");
    setData(await response.json() as Payload); setMessage(null);
  }, [organizationId]);
  useEffect(() => { void load(); }, [load]);
  const personNameById = useMemo(() => new Map(data?.people.map((person) => [person.id, person.full_name]) ?? []), [data]);
  const customerNameById = useMemo(() => new Map(data?.customers.map((customer) => [customer.id, customer.trade_name || customer.legal_name]) ?? []), [data]);
  const groups = useMemo(() => {
    const values = new Map<string, Center[]>();
    for (const center of data?.centers ?? []) { const key = center.code.split(".")[0] || "Otros"; values.set(key, [...(values.get(key) ?? []), center]); }
    return [...values.entries()].sort(([a], [b]) => a.localeCompare(b, "es", { numeric: true })).map(([key, centers]) => { const sorted = centers.sort((a, b) => a.code.localeCompare(b.code, "es", { numeric: true })); return { key, centers: sorted, name: sorted.find((center) => center.code === `${key}.0.0.0`)?.name ?? `Grupo ${key}` }; });
  }, [data]);
  useEffect(() => { if (groups.length) setExpandedGroups((current) => current.length ? current : [groups[0].key]); }, [groups]);

  async function submit(action: string, values: Record<string, unknown>) {
    if (!organizationId || saving) return;
    setSaving(true); setMessage(null);
    const response = await fetch("/api/cost-centers", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, action, ...values }) });
    setSaving(false);
    if (!response.ok) return setMessage("No fue posible guardar la imputación. Revisa los datos e inténtalo nuevamente.");
    setMessage("Centro actualizado con registros existentes."); await load();
  }
  function openCenter(center: Center) { setSelectedCenter(center); setIssuedId(""); setReceivedId(""); setModalPersonId(""); setModalAllocation("100"); setModalDate(today()); }
  function toggleCenterSort(key: typeof centerSort.key) { setCenterSort((current) => current.key === key ? { key, direction: current.direction === "asc" ? "desc" : "asc" } : { key, direction: "asc" }); }
  function sortCenters(centers: Center[]) { return [...centers].sort((left, right) => { const peopleLeft = data?.assignments.filter((item) => item.cost_center_id === left.id).length ?? 0; const peopleRight = data?.assignments.filter((item) => item.cost_center_id === right.id).length ?? 0; const customersLeft = data?.customerLinks.filter((item) => item.cost_center_id === left.id).length ?? 0; const customersRight = data?.customerLinks.filter((item) => item.cost_center_id === right.id).length ?? 0; const movementsLeft = (data?.issuedDocuments.filter((item) => item.cost_center_id === left.id).length ?? 0) + (data?.receivedDocuments.filter((item) => item.cost_center_id === left.id).length ?? 0); const movementsRight = (data?.issuedDocuments.filter((item) => item.cost_center_id === right.id).length ?? 0) + (data?.receivedDocuments.filter((item) => item.cost_center_id === right.id).length ?? 0); const comparison = centerSort.key === "center" ? left.code.localeCompare(right.code, "es", { numeric: true }) : centerSort.key === "people" ? peopleLeft - peopleRight : centerSort.key === "customers" ? customersLeft - customersRight : movementsLeft - movementsRight; return centerSort.direction === "asc" ? comparison : -comparison; }); }
  function createCenter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void submit("create_center", { code: centerCode, name: centerName }).then(() => { setCenterCode(""); setCenterName(""); }); }
  function attachDocument(event: FormEvent<HTMLFormElement>, action: "assign_issued_document" | "assign_received_document", documentId: string) { event.preventDefault(); if (selectedCenter && documentId) void submit(action, { costCenterId: selectedCenter.id, documentId }); }
  function attachPerson(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (selectedCenter && modalPersonId) void submit("assign_worker", { costCenterId: selectedCenter.id, personId: modalPersonId, allocationPercentage: modalAllocation, effectiveFrom: modalDate }); }

  const availableIssued = data?.issuedDocuments.filter((document) => !document.cost_center_id || document.cost_center_id === selectedCenter?.id) ?? [];
  const availableReceived = data?.receivedDocuments.filter((document) => !document.cost_center_id || document.cost_center_id === selectedCenter?.id) ?? [];

  return <main className="dashboard cost-centers-dashboard">
    <section className="headline"><div><span className="eyebrow">ESTRUCTURA DE GESTIÓN</span><h1>Centros de costo</h1><p>Abre un centro para cargarle ingresos, gastos o personas que ya están registrados en la plataforma.</p></div></section>
    <section className="table-section cost-center-section"><div className="table-heading"><div><span className="panel-label">MAPA DE CENTROS</span><h2>Centros y registros asociados</h2><p>Selecciona un centro para imputar documentos o dotación existente.</p></div><button type="button" className="secondary-button" onClick={() => void load()} disabled={saving}>Actualizar</button></div>{message && <p className="operation-message">{message}</p>}
      <div className="cost-center-groups">{groups.length ? groups.map((group) => { const open = expandedGroups.includes(group.key); const groupAssignments = data?.assignments.filter((item) => group.centers.some((center) => center.id === item.cost_center_id)) ?? []; const groupIssued = data?.issuedDocuments.filter((item) => group.centers.some((center) => center.id === item.cost_center_id)) ?? []; const groupReceived = data?.receivedDocuments.filter((item) => group.centers.some((center) => center.id === item.cost_center_id)) ?? []; return <section className="cost-center-group" key={group.key}><button type="button" className="cost-center-group-toggle" onClick={() => setExpandedGroups((current) => current.includes(group.key) ? current.filter((key) => key !== group.key) : [...current, group.key])} aria-expanded={open}><span className="cost-center-group-chevron">{open ? "▾" : "▸"}</span><span><strong>{group.key} · {group.name}</strong><small>{group.centers.length} centros · {groupAssignments.length} personas · {groupIssued.length} ingresos · {groupReceived.length} gastos</small></span></button>{open && <div className="table-scroll"><table><thead><tr>{([ ["center", "Centro"], ["people", "Personas"], ["customers", "Clientes"], ["movements", "Movimientos"] ] as const).map(([key, label]) => <th key={key}><button type="button" className="table-sort-button" onClick={() => toggleCenterSort(key)}>{label}{centerSort.key === key ? centerSort.direction === "asc" ? " ↑" : " ↓" : ""}</button></th>)}</tr></thead><tbody>{sortCenters(group.centers).map((center) => { const people = data?.assignments.filter((item) => item.cost_center_id === center.id) ?? []; const customers = data?.customerLinks.filter((item) => item.cost_center_id === center.id) ?? []; const issued = data?.issuedDocuments.filter((item) => item.cost_center_id === center.id) ?? []; const received = data?.receivedDocuments.filter((item) => item.cost_center_id === center.id) ?? []; return <tr key={center.id}><td><button type="button" className="cost-center-select-button" onClick={() => openCenter(center)}><strong>{center.code}</strong><small>{center.name} · Cargar registros</small></button></td><td>{people.length ? people.map((item) => <small key={item.id}>{personNameById.get(item.person_id) ?? "Persona"} · {item.allocation_percentage}%</small>) : "—"}</td><td>{customers.length ? customers.map((item) => <small key={item.id}>{customerNameById.get(item.counterparty_id) ?? "Cliente"} · {item.allocation_percentage}%</small>) : "—"}</td><td><small>{issued.length} ingreso(s)</small><small>{received.length} gasto(s)</small></td></tr>; })}</tbody></table></div>}</section>; }) : <p className="billing-empty">Crea el primer centro de costo para comenzar.</p>}</div>
      <details className="cost-center-management-panel"><summary><span><strong>Crear un centro nuevo</strong><small>La asignación de personas, ingresos y gastos se hace desde cada centro.</small></span><span className="cost-center-management-hint">Abrir</span></summary><div className="admin-grid"><article className="panel"><div className="panel-heading"><div><span className="panel-label">ESTRUCTURA</span><h2>Nuevo centro</h2></div></div><form className="admin-form" onSubmit={createCenter}><label>Código<input value={centerCode} maxLength={40} placeholder="PROY-001" onChange={(event) => setCenterCode(event.target.value)} required /></label><label>Nombre<input value={centerName} maxLength={160} placeholder="Proyecto o unidad" onChange={(event) => setCenterName(event.target.value)} required /></label><button className="secondary-button" disabled={saving}>Crear centro</button></form></article></div></details>
    </section>
    {selectedCenter && <div className="modal-backdrop" role="presentation"><section className="entry-modal cost-center-load-modal" role="dialog" aria-modal="true" aria-labelledby="cost-center-load-title"><div className="modal-header"><div><span className="eyebrow">CARGAR REGISTROS AL CENTRO</span><h2 id="cost-center-load-title">{selectedCenter.code} · {selectedCenter.name}</h2><p>Los documentos se imputan 100% a este centro. Puedes modificar la asignación más adelante.</p></div><button type="button" className="close-button" onClick={() => setSelectedCenter(null)} aria-label="Cerrar">×</button></div><div className="cost-center-load-grid"><form onSubmit={(event) => attachDocument(event, "assign_issued_document", issuedId)}><span className="panel-label">INGRESOS</span><h3>Factura emitida</h3><label>Documento<select required value={issuedId} onChange={(event) => setIssuedId(event.target.value)}><option value="">Selecciona un ingreso</option>{availableIssued.map((document) => <option key={document.id} value={document.id}>{document.issue_date || "Sin fecha"} · {document.client_name || "Cliente"} · #{document.document_number || "—"} · {money.format(Number(document.total_amount ?? 0))}</option>)}</select></label><button className="secondary-button" disabled={saving || !issuedId}>Cargar ingreso</button></form><form onSubmit={(event) => attachDocument(event, "assign_received_document", receivedId)}><span className="panel-label">GASTOS</span><h3>Factura recibida</h3><label>Documento<select required value={receivedId} onChange={(event) => setReceivedId(event.target.value)}><option value="">Selecciona un gasto</option>{availableReceived.map((document) => <option key={document.id} value={document.id}>{document.issue_date} · {document.supplier_name} · #{document.document_number || "—"} · {money.format(Number(document.total_amount ?? 0))}</option>)}</select></label><button className="secondary-button" disabled={saving || !receivedId}>Cargar gasto</button></form><form onSubmit={attachPerson}><span className="panel-label">PERSONAS</span><h3>Dotación existente</h3><label>Persona<select required value={modalPersonId} onChange={(event) => setModalPersonId(event.target.value)}><option value="">Selecciona una persona</option>{data?.people.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><label>% de imputación<input required type="number" min="0.01" max="100" step="0.01" value={modalAllocation} onChange={(event) => setModalAllocation(event.target.value)} /></label><label>Vigente desde<input required type="date" value={modalDate} onChange={(event) => setModalDate(event.target.value)} /></label><button className="secondary-button" disabled={saving || !modalPersonId}>Cargar persona</button></form></div></section></div>}
  </main>;
}
