"use client";

import { useEffect, useMemo, useState } from "react";

type Module = "Cuentas por cobrar" | "Cuentas por pagar" | "Aprobaciones" | "Tesorería" | "Recurrentes" | "Imputaciones pendientes";
type Item = { id: string; document_number?: string | null; payable_number?: string; client_name?: string | null; supplier_name?: string; due_date?: string | null; total_amount?: number | string; };
type Payload = { year: string; controls: { overdueReceivables: Item[]; overdueReceivableCount: number; overduePayables: Item[]; overduePayableCount: number; approvals: Array<{ id: string; title: string; target_type: string; amount: number | string; currency_code: string; submitted_at: string }>; executions: Array<{ id: string; direction: string; amount: number | string; executed_on: string; payment_reference: string | null }>; billingAlerts: Array<{ id: string; alert_type: string; last_detected_at: string }>; missingCostCenter: number; } };
const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
const date = (value: string | null | undefined) => value ? new Intl.DateTimeFormat("es-CL", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : "—";

export function ManagementCenter({ organizationId, onNavigate }: { organizationId: string | null; onNavigate: (module: Module) => void }) {
  const [year, setYear] = useState(String(new Date().getFullYear())); const [data, setData] = useState<Payload | null>(null); const [loading, setLoading] = useState(true);
  async function load() { if (!organizationId) { setData(null); setLoading(false); return; } setLoading(true); const response = await fetch(`/api/management-center?organizationId=${organizationId}&year=${year}`, { cache: "no-store" }); setData(response.ok ? await response.json() as Payload : null); setLoading(false); }
  useEffect(() => { void load(); }, [organizationId, year]);
  const controls = data?.controls; const years = useMemo(() => [Number(year) - 1, Number(year), Number(year) + 1], [year]);
  const cards: Array<{ label: string; value: number; detail: string; module: Module; tone?: string }> = controls ? [
    { label: "Cobranza vencida", value: controls.overdueReceivableCount, detail: "Documentos vencidos por gestionar", module: "Cuentas por cobrar", tone: "danger" },
    { label: "Pagos vencidos", value: controls.overduePayableCount, detail: "Obligaciones aprobadas o recibidas", module: "Cuentas por pagar", tone: "danger" },
    { label: "Aprobaciones", value: controls.approvals.length, detail: "Decisiones pendientes", module: "Aprobaciones" },
    { label: "Ejecutado sin cartola", value: controls.executions.length, detail: "Control bancario pendiente", module: "Tesorería" },
    { label: "Imputaciones pendientes", value: controls.missingCostCenter, detail: "Registros sin centro de costo", module: "Imputaciones pendientes" },
    { label: "Alertas de facturación", value: controls.billingAlerts.length, detail: "Ciclos recurrentes abiertos", module: "Recurrentes" },
  ] : [];
  return <main className="dashboard management-center"><section className="headline"><div><span className="eyebrow">CENTRO DE GESTIÓN · ERP / CRM</span><h1>Prioridades de la empresa</h1><p>Una lectura operativa anual: cada indicador abre el proceso que requiere acción, sin mezclar períodos ni inventar saldos.</p></div><div className="headline-actions"><label className="period-picker">Año contable<select value={year} onChange={(event) => setYear(event.target.value)}>{years.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><button type="button" className="secondary-button" onClick={() => void load()} disabled={loading}>{loading ? "Actualizando…" : "Actualizar"}</button></div></section><section className="kpis management-kpis">{loading ? <p className="billing-empty">Construyendo prioridades de gestión…</p> : cards.map((card) => <button key={card.label} type="button" className={`kpi-card kpi-card-button ${card.tone ?? ""}`} onClick={() => onNavigate(card.module)}><span>{card.label}</span><strong>{card.value}</strong><small>{card.detail} · Ver detalle</small></button>)}</section>{!loading && controls && <section className="management-worklists"><section className="table-section"><div className="table-heading"><div><span className="panel-label">COBRANZA PRIORITARIA</span><h2>Vencidos del período</h2></div><button className="secondary-button" type="button" onClick={() => onNavigate("Cuentas por cobrar")}>Gestionar cartera</button></div><div className="table-scroll"><table><thead><tr><th>Cliente / documento</th><th>Vencimiento</th><th className="money-col">Monto</th></tr></thead><tbody>{controls.overdueReceivables.length ? controls.overdueReceivables.map((item) => <tr key={item.id}><td><strong>{item.client_name || "Cliente sin nombre"}</strong><small>Folio {item.document_number || "—"}</small></td><td>{date(item.due_date)}</td><td className="money-col is-negative">{money.format(Number(item.total_amount ?? 0))}</td></tr>) : <tr><td colSpan={3}>Sin documentos vencidos en este período.</td></tr>}</tbody></table></div></section><section className="table-section"><div className="table-heading"><div><span className="panel-label">DECISIONES Y CAJA</span><h2>Lo que requiere intervención</h2></div></div><div className="management-action-list"><button type="button" onClick={() => onNavigate("Aprobaciones")}><strong>{controls.approvals.length} aprobación(es) pendiente(s)</strong><span>Abre la bandeja de decisiones</span></button><button type="button" onClick={() => onNavigate("Tesorería")}><strong>{controls.executions.length} ejecución(es) sin respaldo bancario</strong><span>Revisa cartola y conciliación</span></button><button type="button" onClick={() => onNavigate("Imputaciones pendientes")}><strong>{controls.missingCostCenter} registro(s) sin centro de costo</strong><span>Completa la calidad de gestión</span></button></div></section></section>}</main>;
}
