"use client";

import { useEffect, useMemo, useState } from "react";
import { Bar, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type LaborCostBasis = "official" | "posted_provision" | "missing";
type ReportLine = { period: string; revenue: number; expenses: number; receivedExpenses: number; directExpenses: number; laborCost: number; laborCostBasis: LaborCostBasis; laborCostAvailable: boolean; recognizedExpenses: number; operatingResult: number; budgetRevenue: number | null; budgetExpense: number | null; budgetResult: number | null; forecastRevenue: number | null; forecastExpense: number | null; forecastResult: number | null; isClosedPeriod: boolean };
type CenterPerformance = { code: string; name: string; revenue: number; laborCost: number; expenses: number; result: number };
type Commercial = { totalReceivable: number; overdueReceivable: number; dueNextSevenDays: number; pendingDocuments: number; averageCollectionDays: number | null; openPurchaseOrderBalance: number; recurringMonthlyCommitment: number };
type ReportPayload = { incomeStatement: ReportLine[]; centerPerformance: CenterPerformance[]; commercial: Commercial };

const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
const percentage = new Intl.NumberFormat("es-CL", { style: "percent", maximumFractionDigits: 1 });
const shortMonth = (period: string) => new Intl.DateTimeFormat("es-CL", { month: "short" }).format(new Date(`${period}-01T00:00:00`));
const moneyCell = (value: number | null) => value === null ? "—" : money.format(value);

export function ReportsDashboard({ organizationId }: { organizationId: string | null }) {
  const [year, setYear] = useState(() => new Date().getFullYear());
  const [payload, setPayload] = useState<ReportPayload | null>(null);
  const [showMonthlyDetail, setShowMonthlyDetail] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    if (!organizationId) return;
    fetch(`/api/integrations/peoplework/summary?organizationId=${encodeURIComponent(organizationId)}&year=${year}`, { cache: "no-store" }).then(async (response) => response.ok ? response.json() as Promise<ReportPayload> : Promise.reject()).then((next) => { setPayload(next); setError(null); }).catch(() => setError("No fue posible cargar la Dirección Financiera con tu sesión actual."));
  }, [organizationId, year]);

  const lines = payload?.incomeStatement ?? [];
  const centers = payload?.centerPerformance ?? [];
  const commercial = payload?.commercial;
  const totals = useMemo(() => lines.reduce((total, line) => ({
    revenue: total.revenue + line.revenue,
    coveredRevenue: total.coveredRevenue + (line.laborCostAvailable ? line.revenue : 0),
    expenses: total.expenses + line.expenses,
    receivedExpenses: total.receivedExpenses + line.receivedExpenses,
    directExpenses: total.directExpenses + line.directExpenses,
    laborCost: total.laborCost + (line.laborCostAvailable ? line.laborCost : 0),
    operatingResult: total.operatingResult + (line.laborCostAvailable ? line.operatingResult : 0),
    budgetRevenue: total.budgetRevenue + (line.budgetRevenue ?? 0),
    budgetExpense: total.budgetExpense + (line.budgetExpense ?? 0),
    budgetResult: total.budgetResult + (line.budgetResult ?? 0),
    forecastRevenue: total.forecastRevenue + (line.forecastRevenue ?? 0),
    forecastResult: total.forecastResult + (line.forecastResult ?? 0),
    coveredMonths: total.coveredMonths + (line.laborCostAvailable ? 1 : 0),
    officialMonths: total.officialMonths + (line.laborCostBasis === "official" ? 1 : 0),
    provisionMonths: total.provisionMonths + (line.laborCostBasis === "posted_provision" ? 1 : 0),
    closedRevenue: total.closedRevenue + (line.isClosedPeriod ? line.revenue : 0),
    closedBudget: total.closedBudget + (line.isClosedPeriod ? (line.budgetRevenue ?? 0) : 0),
  }), { revenue: 0, coveredRevenue: 0, expenses: 0, receivedExpenses: 0, directExpenses: 0, laborCost: 0, operatingResult: 0, budgetRevenue: 0, budgetExpense: 0, budgetResult: 0, forecastRevenue: 0, forecastResult: 0, coveredMonths: 0, officialMonths: 0, provisionMonths: 0, closedRevenue: 0, closedBudget: 0 }), [lines]);
  const planVariance = totals.closedRevenue - totals.closedBudget;
  const contributionMargin = totals.coveredRevenue ? totals.operatingResult / totals.coveredRevenue : null;
  const revenueCoverage = totals.laborCost ? totals.coveredRevenue / totals.laborCost : null;
  const chartData = lines.map((line) => ({ month: shortMonth(line.period), real: line.revenue, gastos: line.expenses, presupuesto: line.budgetRevenue, forecast: line.forecastRevenue, laborCost: line.laborCostAvailable ? line.laborCost : null }));
  const financialRows = [
    { label: "Ingresos netos reales", values: lines.map((line) => line.revenue), total: totals.revenue, tone: "income" },
    { label: "(−) Documentos recibidos de proveedores", values: lines.map((line) => line.receivedExpenses), total: totals.receivedExpenses, tone: "expense" },
    { label: "(−) Cuentas directas / honorarios", values: lines.map((line) => line.directExpenses), total: totals.directExpenses, tone: "expense" },
    { label: "(−) Costo laboral reconocido", values: lines.map((line) => line.laborCostAvailable ? line.laborCost : null), total: totals.laborCost, tone: "expense" },
    { label: "Resultado operativo reconocido", values: lines.map((line) => line.laborCostAvailable ? line.operatingResult : null), total: totals.operatingResult, tone: "result" },
    { label: "Ingresos presupuestados", values: lines.map((line) => line.budgetRevenue), total: totals.budgetRevenue, tone: "plan" },
    { label: "(−) Gastos presupuestados", values: lines.map((line) => line.budgetExpense), total: totals.budgetExpense, tone: "expense" },
    { label: "Resultado simple presupuestado", values: lines.map((line) => line.budgetResult), total: totals.budgetResult, tone: "plan" },
    { label: "Ingresos forecast de cierre", values: lines.map((line) => line.forecastRevenue), total: totals.forecastRevenue, tone: "forecast" },
    { label: "Resultado simple forecast", values: lines.map((line) => line.forecastResult), total: totals.forecastResult, tone: "forecast" },
  ];

  return <main className="dashboard reports-dashboard"><section className="headline"><div><span className="eyebrow">DIRECCIÓN FINANCIERA</span><h1>Resultado, proyección y disciplina comercial</h1><p>El costo laboral reconocido usa nómina real cuando existe y, en su ausencia, la última provisión contabilizada. Los borradores nunca impactan estos KPI.</p></div><div className="headline-actions"><label className="period-picker">Período<select value={year} onChange={(event) => setYear(Number(event.target.value))}>{Array.from({ length: Math.min(7, new Date().getFullYear() - 2019) }, (_, index) => new Date().getFullYear() - index).map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div></section>{error && <p className="operation-message">{error}</p>}
    <section className="kpis kpis-six"><article className="kpi-card" data-help="Facturas y documentos exentos, menos notas de crédito. No incorpora órdenes de compra."><span>Ingresos netos reales</span><strong>{money.format(totals.revenue)}</strong><small>Devengados en {year}</small></article><article className="kpi-card" data-help="Documentos recibidos netos de IVA, más cuentas directas u honorarios aprobados."><span>Gastos registrados</span><strong>{money.format(totals.expenses)}</strong><small>{money.format(totals.receivedExpenses)} proveedores · {money.format(totals.directExpenses)} directos/honorarios</small></article><article className="kpi-card accent" data-help="Usa nómina real o provisión contabilizada con precedencia excluyente; nunca suma ambas."><span>Resultado operativo</span><strong>{totals.coveredMonths === 0 || contributionMargin === null ? "—" : percentage.format(contributionMargin)}</strong><small>{totals.coveredMonths === 0 ? "Falta costo laboral reconocido" : `${money.format(totals.operatingResult)} · ${totals.coveredMonths} mes(es)`}</small></article><article className="kpi-card" data-help="Facturación real de meses cerrados versus el presupuesto de esos mismos meses."><span>Desviación plan cerrado</span><strong className={planVariance < 0 ? "is-negative" : ""}>{money.format(planVariance)}</strong><small>{totals.closedBudget ? percentage.format(totals.closedRevenue / totals.closedBudget - 1) : "Sin plan activo"}</small></article><article className="kpi-card" data-help="Documentos pendientes con vencimiento superado. Es una alerta de cobranza, no saldo bancario."><span>Cartera vencida</span><strong className={commercial && commercial.overdueReceivable > 0 ? "is-negative" : ""}>{money.format(commercial?.overdueReceivable ?? 0)}</strong><small>{commercial?.pendingDocuments ?? 0} documento(s) pendientes</small></article><article className="kpi-card" data-help="Saldo vigente de órdenes de compra no facturado. Es compromiso comercial, no ingreso devengado."><span>Backlog de OC</span><strong>{money.format(commercial?.openPurchaseOrderBalance ?? 0)}</strong><small>Compromiso aún por facturar</small></article></section>
    <section className="analysis-strip executive-insights"><article><span>COBERTURA LABORAL</span><strong>{revenueCoverage === null ? "Sin costo reconocido" : `${revenueCoverage.toFixed(2)}x`}</strong><p>Ingresos de los {totals.coveredMonths} meses cubiertos por cada peso de costo laboral reconocido.</p></article><article><span>ORIGEN LABORAL</span><strong>{totals.officialMonths} real · {totals.provisionMonths} provisión</strong><p>Cada mes usa una sola fuente para evitar dobles conteos.</p></article><article><span>COBRANZA PRÓXIMA</span><strong>{money.format(commercial?.dueNextSevenDays ?? 0)}</strong><p>Cartera pendiente que vence dentro de los próximos siete días.</p></article><article><span>CICLO DE COBRO</span><strong>{commercial?.averageCollectionDays === null || commercial?.averageCollectionDays === undefined ? "Sin observación" : `${Math.round(commercial.averageCollectionDays)} días`}</strong><p>Promedio observado sólo en documentos con emisión y pago registrado.</p></article></section>
    <section className="report-grid"><article className="panel report-chart-panel"><div className="panel-heading"><div><span className="panel-label">EJECUCIÓN Y CIERRE</span><h2>Ingresos reales, gastos y plan</h2><p>El forecast toma real completo en meses cerrados y el presupuesto total en meses futuros, sin restar dos veces remuneraciones.</p></div><span className="unit">CLP neto/exento</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: "#7e8ba0", fontSize: 11 }} /><YAxis hide /><Tooltip formatter={(value) => money.format(Number(value))} contentStyle={{ borderRadius: 10, border: "1px solid #e6e9ef" }} /><Bar dataKey="real" name="Ingresos reales" fill="#5968df" radius={[5, 5, 0, 0]} /><Bar dataKey="gastos" name="Gastos documentados" fill="#d98154" radius={[5, 5, 0, 0]} /><Bar dataKey="presupuesto" name="Presupuesto" fill="#aab4c8" radius={[5, 5, 0, 0]} /><Line type="monotone" dataKey="forecast" name="Forecast" stroke="#1ca879" strokeWidth={2.5} dot={false} /><Line type="monotone" dataKey="laborCost" name="Costo laboral reconocido" stroke="#d85f6c" strokeWidth={2} strokeDasharray="5 4" dot={false} /></ComposedChart></ResponsiveContainer></div></article><article className="panel report-quality-panel"><div className="panel-heading"><div><span className="panel-label">INTEGRIDAD DEL REPORTE</span><h2>Qué representa cada resultado</h2></div></div><div className="report-quality-list"><p><strong>Costo laboral:</strong> {totals.officialMonths} mes(es) con nómina real y {totals.provisionMonths} con provisión contabilizada; el borrador queda fuera.</p><p><strong>Resultado operativo:</strong> se calcula sólo sobre los {totals.coveredMonths} meses con costo laboral reconocido, incluido el denominador del margen.</p><p><strong>Plan y forecast:</strong> el presupuesto de gastos se trata como total; en meses cerrados se reemplaza por gasto documentado más costo laboral.</p></div></article></section>
    <section className="table-section financial-statement-section"><div className="table-heading"><div><span className="panel-label">EERR GERENCIAL · {year}</span><h2>Evolución mensual y cierre de año</h2><p>Meses como columnas para lectura evolutiva. Puedes contraer el detalle cuando necesites concentrarte en los indicadores.</p></div><button type="button" className="secondary-button" onClick={() => setShowMonthlyDetail((current) => !current)}>{showMonthlyDetail ? "Contraer meses" : "Ver meses"}</button></div>{showMonthlyDetail && <div className="table-scroll"><table className="financial-matrix"><thead><tr><th>Concepto</th>{lines.map((line) => <th className="money-col" key={line.period}>{shortMonth(line.period)}</th>)}<th className="money-col total-column">Año</th></tr></thead><tbody>{financialRows.map((row) => <tr key={row.label} className={`matrix-row ${row.tone}`}><td>{row.label}</td>{row.values.map((value, index) => <td className="money-col" key={`${row.label}-${index}`}>{moneyCell(value)}</td>)}<td className="money-col total-column">{money.format(row.total)}</td></tr>)}</tbody></table></div>}</section>
    <section className="table-section"><div className="table-heading"><div><span className="panel-label">RENTABILIDAD POR CENTRO</span><h2>Ingresos, gastos y costo laboral reconocido</h2><p>La suma de centros, incluido “SIN-CENTRO”, cuadra con el costo laboral del EERR. Los componentes corporativos se distribuyen según la base PeopleWork.</p></div></div><div className="table-scroll"><table><thead><tr><th>Centro de costo</th><th className="money-col">Ingresos atribuidos</th><th className="money-col">Costo laboral reconocido</th><th className="money-col">Gastos directos imputados</th><th className="money-col">Margen tras gastos</th><th className="money-col">Margen</th></tr></thead><tbody>{centers.length ? centers.map((center) => <tr key={center.code}><td><strong>{center.code}</strong><small>{center.name}</small></td><td className="money-col">{money.format(center.revenue)}</td><td className="money-col">{money.format(center.laborCost)}</td><td className="money-col">{money.format(center.expenses)}</td><td className={`money-col ${center.result < 0 ? "is-negative" : ""}`}>{money.format(center.result)}</td><td className="money-col">{center.revenue ? percentage.format(center.result / center.revenue) : "—"}</td></tr>) : <tr><td colSpan={6}>Configura centros, personas y clientes compensadores para habilitar esta lectura.</td></tr>}</tbody></table></div></section>
  </main>;
}
