"use client";

import { useEffect, useMemo, useState } from "react";
import { Bar, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type ReportLine = { period: string; revenue: number; expenses: number; payroll: number; operatingResultBeforeOtherExpenses: number; payrollAvailable: boolean; budgetRevenue: number | null; budgetExpense: number | null; budgetResult: number | null; forecastRevenue: number | null; forecastExpense: number | null; forecastResult: number | null; isClosedPeriod: boolean };
type CenterPerformance = { code: string; name: string; revenue: number; payroll: number; result: number };
type Commercial = { totalReceivable: number; overdueReceivable: number; dueNextSevenDays: number; pendingDocuments: number; averageCollectionDays: number | null; openPurchaseOrderBalance: number; recurringMonthlyCommitment: number };
type ReportPayload = { incomeStatement: ReportLine[]; centerPerformance: CenterPerformance[]; commercial: Commercial };

const money = new Intl.NumberFormat("es-CL", { style: "currency", currency: "CLP", maximumFractionDigits: 0 });
const percentage = new Intl.NumberFormat("es-CL", { style: "percent", maximumFractionDigits: 1 });
const shortMonth = (period: string) => new Intl.DateTimeFormat("es-CL", { month: "short" }).format(new Date(`${period}-01T00:00:00`));
const moneyCell = (value: number | null) => value === null ? "—" : money.format(value);

export function ReportsDashboard({ organizationId }: { organizationId: string | null }) {
  const [year, setYear] = useState(() => new Date().getFullYear());
  const [payload, setPayload] = useState<ReportPayload | null>(null);
  const [showMonthlyDetail, setShowMonthlyDetail] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => {
    if (!organizationId) return;
    fetch(`/api/integrations/peoplework/summary?organizationId=${encodeURIComponent(organizationId)}&year=${year}`).then(async (response) => response.ok ? response.json() as Promise<ReportPayload> : Promise.reject()).then((next) => { setPayload(next); setError(null); }).catch(() => setError("No fue posible cargar la Dirección Financiera con tu sesión actual."));
  }, [organizationId, year]);

  const lines = payload?.incomeStatement ?? [];
  const centers = payload?.centerPerformance ?? [];
  const commercial = payload?.commercial;
  const totals = useMemo(() => lines.reduce((total, line) => ({ revenue: total.revenue + line.revenue, expenses: total.expenses + line.expenses, payroll: total.payroll + (line.payrollAvailable ? line.payroll : 0), contribution: total.contribution + (line.payrollAvailable ? line.operatingResultBeforeOtherExpenses : 0), budgetRevenue: total.budgetRevenue + (line.budgetRevenue ?? 0), budgetExpense: total.budgetExpense + (line.budgetExpense ?? 0), budgetResult: total.budgetResult + (line.budgetResult ?? 0), forecastRevenue: total.forecastRevenue + (line.forecastRevenue ?? 0), forecastResult: total.forecastResult + (line.forecastResult ?? 0), payrollMonths: total.payrollMonths + (line.payrollAvailable ? 1 : 0), closedRevenue: total.closedRevenue + (line.isClosedPeriod ? line.revenue : 0), closedBudget: total.closedBudget + (line.isClosedPeriod ? (line.budgetRevenue ?? 0) : 0) }), { revenue: 0, expenses: 0, payroll: 0, contribution: 0, budgetRevenue: 0, budgetExpense: 0, budgetResult: 0, forecastRevenue: 0, forecastResult: 0, payrollMonths: 0, closedRevenue: 0, closedBudget: 0 }), [lines]);
  const planVariance = totals.closedRevenue - totals.closedBudget;
  const contributionMargin = totals.revenue ? totals.contribution / totals.revenue : null;
  const revenueCoverage = totals.payroll ? totals.revenue / totals.payroll : null;
  const chartData = lines.map((line) => ({ month: shortMonth(line.period), real: line.revenue, gastos: line.expenses, presupuesto: line.budgetRevenue, forecast: line.forecastRevenue, payroll: line.payrollAvailable ? line.payroll : null }));
  const financialRows = [
    { label: "Ingresos netos reales", values: lines.map((line) => line.revenue), total: totals.revenue, tone: "income" },
    { label: "(−) Gastos documentados de proveedores", values: lines.map((line) => line.expenses), total: totals.expenses, tone: "expense" },
    { label: "(−) Remuneración contractual", values: lines.map((line) => line.payrollAvailable ? line.payroll : null), total: totals.payroll, tone: "expense" },
    { label: "Resultado operativo documentado", values: lines.map((line) => line.payrollAvailable ? line.operatingResultBeforeOtherExpenses : null), total: totals.contribution, tone: "result" },
    { label: "Ingresos presupuestados", values: lines.map((line) => line.budgetRevenue), total: totals.budgetRevenue, tone: "plan" },
    { label: "(−) Gastos presupuestados", values: lines.map((line) => line.budgetExpense), total: totals.budgetExpense, tone: "expense" },
    { label: "Resultado simple presupuestado", values: lines.map((line) => line.budgetResult), total: totals.budgetResult, tone: "plan" },
    { label: "Ingresos forecast de cierre", values: lines.map((line) => line.forecastRevenue), total: totals.forecastRevenue, tone: "forecast" },
    { label: "Resultado simple forecast", values: lines.map((line) => line.forecastResult), total: totals.forecastResult, tone: "forecast" },
  ];

  return <main className="dashboard reports-dashboard"><section className="headline"><div><span className="eyebrow">DIRECCIÓN FINANCIERA</span><h1>Resultado, proyección y disciplina comercial</h1><p>Lectura para decisión basada en documentos emitidos, gastos documentados, remuneración contractual y la versión presupuestaria activa.</p></div><div className="headline-actions"><label className="period-picker">Período<select value={year} onChange={(event) => setYear(Number(event.target.value))}>{Array.from({ length: Math.min(7, new Date().getFullYear() - 2019) }, (_, index) => new Date().getFullYear() - index).map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div></section>{error && <p className="operation-message">{error}</p>}
    <section className="kpis kpis-six"><article className="kpi-card" data-help="Facturas y documentos exentos, menos notas de crédito. No incorpora órdenes de compra."><span>Ingresos netos reales</span><strong>{money.format(totals.revenue)}</strong><small>Devengados en {year}</small></article><article className="kpi-card" data-help="Facturas recibidas y notas de crédito de proveedores, netas de IVA."><span>Gastos documentados</span><strong>{money.format(totals.expenses)}</strong><small>Devengados en {year}</small></article><article className="kpi-card accent" data-help="Ingresos netos menos gastos documentados y remuneración contractual disponible."><span>Resultado operativo</span><strong>{contributionMargin === null ? "—" : percentage.format(contributionMargin)}</strong><small>{money.format(totals.contribution)} documentado</small></article><article className="kpi-card" data-help="Facturación real de meses cerrados versus el presupuesto de esos mismos meses."><span>Desviación plan cerrado</span><strong className={planVariance < 0 ? "is-negative" : ""}>{money.format(planVariance)}</strong><small>{totals.closedBudget ? percentage.format(totals.closedRevenue / totals.closedBudget - 1) : "Sin plan activo"}</small></article><article className="kpi-card" data-help="Documentos pendientes con vencimiento superado. Es una alerta de cobranza, no saldo bancario."><span>Cartera vencida</span><strong className={commercial && commercial.overdueReceivable > 0 ? "is-negative" : ""}>{money.format(commercial?.overdueReceivable ?? 0)}</strong><small>{commercial?.pendingDocuments ?? 0} documento(s) pendientes</small></article><article className="kpi-card" data-help="Saldo vigente de órdenes de compra no facturado. Es compromiso comercial, no ingreso devengado."><span>Backlog de OC</span><strong>{money.format(commercial?.openPurchaseOrderBalance ?? 0)}</strong><small>Compromiso aún por facturar</small></article></section>
    <section className="analysis-strip executive-insights"><article><span>COBERTURA LABORAL</span><strong>{revenueCoverage === null ? "Sin costo sincronizado" : `${revenueCoverage.toFixed(2)}x`}</strong><p>Ingresos reales por cada peso de remuneración contractual disponible.</p></article><article><span>RECURRENCIA</span><strong>{money.format(commercial?.recurringMonthlyCommitment ?? 0)} / mes</strong><p>Base mensual de reglas recurrentes activas, antes de su facturación efectiva.</p></article><article><span>COBRANZA PRÓXIMA</span><strong>{money.format(commercial?.dueNextSevenDays ?? 0)}</strong><p>Cartera pendiente que vence dentro de los próximos siete días.</p></article><article><span>CICLO DE COBRO</span><strong>{commercial?.averageCollectionDays === null || commercial?.averageCollectionDays === undefined ? "Sin observación" : `${Math.round(commercial.averageCollectionDays)} días`}</strong><p>Promedio observado sólo en documentos con emisión y pago registrado.</p></article></section>
    <section className="report-grid"><article className="panel report-chart-panel"><div className="panel-heading"><div><span className="panel-label">EJECUCIÓN Y CIERRE</span><h2>Ingresos reales, gastos y plan</h2><p>El forecast toma real en meses cerrados y la versión presupuestaria activa en los meses futuros.</p></div><span className="unit">CLP neto/exento</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={chartData} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fill: "#7e8ba0", fontSize: 11 }} /><YAxis hide /><Tooltip formatter={(value) => money.format(Number(value))} contentStyle={{ borderRadius: 10, border: "1px solid #e6e9ef" }} /><Bar dataKey="real" name="Ingresos reales" fill="#5968df" radius={[5, 5, 0, 0]} /><Bar dataKey="gastos" name="Gastos documentados" fill="#d98154" radius={[5, 5, 0, 0]} /><Bar dataKey="presupuesto" name="Presupuesto" fill="#aab4c8" radius={[5, 5, 0, 0]} /><Line type="monotone" dataKey="forecast" name="Forecast" stroke="#1ca879" strokeWidth={2.5} dot={false} /><Line type="monotone" dataKey="payroll" name="Remuneración contractual" stroke="#d85f6c" strokeWidth={2} strokeDasharray="5 4" dot={false} /></ComposedChart></ResponsiveContainer></div></article><article className="panel report-quality-panel"><div className="panel-heading"><div><span className="panel-label">INTEGRIDAD DEL REPORTE</span><h2>Qué representa cada resultado</h2></div></div><div className="report-quality-list"><p><strong>Resultado operativo:</strong> ingresos reales menos gastos documentados y remuneración contractual; disponible en {totals.payrollMonths} de 12 meses.</p><p><strong>Plan y forecast:</strong> toman sólo la versión presupuestaria activa, no el archivo estático.</p><p><strong>Flujo de caja:</strong> se consulta en Planificación financiera y usa banco, vencimientos y ajustes trazables.</p></div></article></section>
    <section className="table-section financial-statement-section"><div className="table-heading"><div><span className="panel-label">EERR GERENCIAL · {year}</span><h2>Evolución mensual y cierre de año</h2><p>Meses como columnas para lectura evolutiva. Puedes contraer el detalle cuando necesites concentrarte en los indicadores.</p></div><button type="button" className="secondary-button" onClick={() => setShowMonthlyDetail((current) => !current)}>{showMonthlyDetail ? "Contraer meses" : "Ver meses"}</button></div>{showMonthlyDetail && <div className="table-scroll"><table className="financial-matrix"><thead><tr><th>Concepto</th>{lines.map((line) => <th className="money-col" key={line.period}>{shortMonth(line.period)}</th>)}<th className="money-col total-column">Año</th></tr></thead><tbody>{financialRows.map((row) => <tr key={row.label} className={`matrix-row ${row.tone}`}><td>{row.label}</td>{row.values.map((value, index) => <td className="money-col" key={`${row.label}-${index}`}>{moneyCell(value)}</td>)}<td className="money-col total-column">{money.format(row.total)}</td></tr>)}</tbody></table></div>}</section>
    <section className="table-section"><div className="table-heading"><div><span className="panel-label">RENTABILIDAD POR CENTRO</span><h2>Ingresos compensados y remuneraciones</h2><p>Los ingresos se atribuyen sólo cuando el cliente está vinculado al centro y el costo responde a la asignación vigente de cada persona.</p></div></div><div className="table-scroll"><table><thead><tr><th>Centro de costo</th><th className="money-col">Ingresos atribuidos</th><th className="money-col">Remuneración imputada</th><th className="money-col">Margen previo a otros gastos</th><th className="money-col">Margen</th></tr></thead><tbody>{centers.length ? centers.map((center) => <tr key={center.code}><td><strong>{center.code}</strong><small>{center.name}</small></td><td className="money-col">{money.format(center.revenue)}</td><td className="money-col">{money.format(center.payroll)}</td><td className={`money-col ${center.result < 0 ? "is-negative" : ""}`}>{money.format(center.result)}</td><td className="money-col">{center.revenue ? percentage.format(center.result / center.revenue) : "—"}</td></tr>) : <tr><td colSpan={5}>Configura centros, personas y clientes compensadores para habilitar esta lectura.</td></tr>}</tbody></table></div></section>
  </main>;
}
