"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { allowedTransitions, statusLabels, type SubscriptionStatus } from "@/lib/virtual-secretary";

type Plan = { id: string; code: string; name: string; duration_months: number; individual_net_price: number | string; company_net_price: number | string; currency_code: string; is_exceptional: boolean; requires_approval: boolean; is_active: boolean };
type Customer = { id: string; legal_name: string; trade_name: string | null; tax_id: string | null; email: string | null; billing_email: string | null };
type Subscription = { id: string; subscription_code: string; plan_id: string; counterparty_id: string; customer_type: "individual" | "company"; billing_contact_email: string; operational_contact_email: string; status: SubscriptionStatus; currency_code: string; list_net_amount: number | string; discount_amount: number | string; net_amount: number | string; tax_amount: number | string; gross_amount: number | string; validated_paid_amount: number | string; payment_validation_amount: number | string; outstanding_amount: number | string; current_start_on: string | null; current_end_on: string | null; next_renewal_on: string | null; due_on: string; automatic_renewal: boolean; activated_at: string | null; created_at: string };
type Payment = { id: string; subscription_id: string; payment_method: string; provider_code: string; amount: number | string; currency_code: string; paid_at: string; validation_status: string; evidence_path: string | null; transfer_reference: string | null };
type TimelineEvent = { id: string | number; subscription_id: string; event_type: string; from_status: string | null; to_status: string | null; reason: string | null; created_at: string };
type Alert = { id: string; subscription_id: string; alert_on: string; priority: string; status: string; action_recommended: string | null; amount: number | string };
type Revenue = { id: string; subscription_id: string; recognition_on: string; amount: number | string; status: string };
type Payload = { role: string; plans: Plan[]; customers: Customer[]; subscriptions: Subscription[]; payments: Payment[]; events: TimelineEvent[]; alerts: Alert[]; revenueSchedule: Revenue[] };

const money = (amount: number | string, currency = "CLP") => new Intl.NumberFormat("es-CL", { style: "currency", currency, maximumFractionDigits: currency === "CLP" ? 0 : 2 }).format(Number(amount) || 0);
const displayDate = (value: string | null) => value ? new Intl.DateTimeFormat("es-CL", { dateStyle: "medium" }).format(new Date(`${value.slice(0, 10)}T12:00:00`)) : "—";
const today = () => new Date().toISOString().slice(0, 10);

export function VirtualSecretarySubscriptions({ organizationId, canManage }: { organizationId: string | null; canManage: boolean }) {
  const [data, setData] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const [selectedId, setSelectedId] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [planFilter, setPlanFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [showSale, setShowSale] = useState(false);
  const [showPayment, setShowPayment] = useState(false);
  const [showPlans, setShowPlans] = useState(false);
  const [busy, setBusy] = useState(false);

  const load = async () => {
    if (!organizationId) return;
    setLoading(true);
    const response = await fetch(`/api/virtual-secretary?organizationId=${encodeURIComponent(organizationId)}`, { cache: "no-store" });
    const payload = await response.json().catch(() => null) as Payload & { error?: string } | null;
    if (response.ok && payload) { setData(payload); setSelectedId((current) => current || payload.subscriptions[0]?.id || ""); }
    else setMessage(payload?.error === "virtual_secretary_is_only_available_for_geimser" ? "Este producto está disponible únicamente en la organización existente Geimser." : "No fue posible cargar Secretaria Virtual.");
    setLoading(false);
  };
  useEffect(() => { void load(); }, [organizationId]);

  const customers = useMemo(() => new Map((data?.customers ?? []).map((row) => [row.id, row])), [data]);
  const plans = useMemo(() => new Map((data?.plans ?? []).map((row) => [row.id, row])), [data]);
  const selected = data?.subscriptions.find((row) => row.id === selectedId) ?? null;
  const filtered = useMemo(() => (data?.subscriptions ?? []).filter((row) => {
    const customer = customers.get(row.counterparty_id);
    const needle = `${row.subscription_code} ${customer?.legal_name ?? ""} ${customer?.trade_name ?? ""} ${customer?.tax_id ?? ""}`.toLowerCase();
    return (statusFilter === "all" || row.status === statusFilter) && (planFilter === "all" || row.plan_id === planFilter) && needle.includes(search.trim().toLowerCase());
  }), [data, customers, search, statusFilter, planFilter]);
  const active = (data?.subscriptions ?? []).filter((row) => row.status === "active");
  const expiring = (data?.subscriptions ?? []).filter((row) => row.status === "expiring");
  const delinquent = (data?.subscriptions ?? []).filter((row) => ["expired_pending_payment", "suspended_nonpayment"].includes(row.status));
  const validatedCollections = (data?.payments ?? []).filter((row) => row.validation_status === "validated").reduce((sum, row) => sum + Number(row.amount), 0);
  const pending = (data?.subscriptions ?? []).reduce((sum, row) => sum + Number(row.outstanding_amount), 0);
  const paidSubscriptionIds = new Set((data?.subscriptions ?? []).filter((row) => Number(row.validated_paid_amount) >= Number(row.gross_amount)).map((row) => row.id));
  const deferred = (data?.revenueSchedule ?? []).filter((row) => row.status === "scheduled" && paidSubscriptionIds.has(row.subscription_id) && row.recognition_on > today()).reduce((sum, row) => sum + Number(row.amount), 0);
  const recognized = (data?.revenueSchedule ?? []).filter((row) => row.status === "recognized").reduce((sum, row) => sum + Number(row.amount), 0);
  const canValidate = data?.role === "administrator" || data?.role === "finance";

  const action = async (body: Record<string, unknown>, success: string) => {
    if (!organizationId) return; setBusy(true); setMessage("");
    const response = await fetch("/api/virtual-secretary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ organizationId, ...body }) });
    const payload = await response.json().catch(() => null) as { detail?: string; error?: string } | null;
    setMessage(response.ok ? success : payload?.detail || "La acción fue rechazada por las reglas de negocio o permisos.");
    if (response.ok) await load(); setBusy(false); return response.ok;
  };

  const transition = async (toStatus: SubscriptionStatus) => {
    if (!selected) return;
    const requiresReason = ["voided", "cancelled", "suspended_nonpayment"].includes(toStatus);
    const reason = requiresReason ? window.prompt("Motivo obligatorio de la acción:") : null;
    if (requiresReason && !reason?.trim()) return;
    await action({ action: "transition", subscriptionId: selected.id, toStatus, reason }, `Suscripción actualizada a ${statusLabels[toStatus]}.`);
  };

  const exportCsv = () => {
    const rows = [["Código", "Cliente", "Plan", "Estado", "Inicio", "Término", "Neto", "Impuesto", "Bruto", "Cobrado validado", "En validación", "Saldo"], ...filtered.map((row) => [row.subscription_code, customers.get(row.counterparty_id)?.legal_name ?? "", plans.get(row.plan_id)?.name ?? "", statusLabels[row.status], row.current_start_on ?? "", row.current_end_on ?? "", row.net_amount, row.tax_amount, row.gross_amount, row.validated_paid_amount, row.payment_validation_amount, row.outstanding_amount])];
    const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(";")).join("\n");
    const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([`\ufeff${csv}`], { type: "text/csv" })); link.download = `secretaria-virtual-${today()}.csv`; link.click(); URL.revokeObjectURL(link.href);
  };

  if (loading) return <section className="panel"><p className="billing-empty">Cargando suscripciones de Secretaria Virtual…</p></section>;
  return <div className="sv-workspace">
    <section className="panel sv-hero"><div><span className="panel-label">SUSCRIPCIONES · GEIMSER</span><h2>Secretaria Virtual</h2><p>Venta, pago anticipado, activación, renovación y devengo en un expediente trazable.</p></div><div className="table-actions"><button className="secondary-button" onClick={exportCsv}>Exportar CSV</button>{canValidate && <button className="secondary-button" onClick={() => setShowPlans(true)}>Planes y precios</button>}{canManage && <button className="primary-button" onClick={() => setShowSale(true)}>Nueva venta</button>}</div></section>
    {message && <p className="operation-message">{message}</p>}
    <section className="sv-kpis">
      <Kpi label="Activas" value={String(active.length)} detail={money(active.reduce((sum, row) => sum + Number(row.gross_amount), 0))} />
      <Kpi label="Próximas a vencer" value={String(expiring.length)} detail={money(expiring.reduce((sum, row) => sum + Number(row.gross_amount), 0))} />
      <Kpi label="Vencidas / suspendidas" value={String(delinquent.length)} detail={money(delinquent.reduce((sum, row) => sum + Number(row.outstanding_amount), 0))} />
      <Kpi label="Cobros validados" value={money(validatedCollections)} detail="Caja confirmada" />
      <Kpi label="Saldo pendiente" value={money(pending)} detail="No incluye pagos en validación" />
      <Kpi label="Ingreso diferido" value={money(deferred)} detail={`Devengado: ${money(recognized)}`} />
    </section>
    <section className="panel sv-control"><div className="sv-filters"><label>Buscar<input type="search" placeholder="Código, cliente o RUT" value={search} onChange={(event) => setSearch(event.target.value)} /></label><label>Estado<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option value="all">Todos</option>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Plan<select value={planFilter} onChange={(event) => setPlanFilter(event.target.value)}><option value="all">Todos</option>{data?.plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.code} · {plan.name}</option>)}</select></label></div>
      <div className="sv-layout"><div className="sv-table-wrap"><table className="data-table sv-table"><thead><tr><th>Suscripción</th><th>Cliente</th><th>Estado</th><th>Vigencia</th><th>Venta / cobro / saldo</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.id} className={selectedId === row.id ? "is-selected" : ""} onClick={() => setSelectedId(row.id)}><td><strong>{row.subscription_code}</strong><small>{plans.get(row.plan_id)?.name ?? "Plan"}</small></td><td><strong>{customers.get(row.counterparty_id)?.trade_name || customers.get(row.counterparty_id)?.legal_name}</strong><small>{customers.get(row.counterparty_id)?.tax_id || (row.customer_type === "individual" ? "Persona natural" : "Sin RUT")}</small></td><td><span className={`sv-status is-${row.status}`}>{statusLabels[row.status]}</span><small>{row.automatic_renewal ? "Renovación automática" : "Renovación manual"}</small></td><td>{displayDate(row.current_end_on)}<small>{displayDate(row.current_start_on)} → {displayDate(row.current_end_on)}</small></td><td><strong>{money(row.gross_amount, row.currency_code)}</strong><small>Validado {money(row.validated_paid_amount, row.currency_code)} · Saldo {money(row.outstanding_amount, row.currency_code)}</small></td></tr>)}</tbody></table>{!filtered.length && <p className="billing-empty">No hay suscripciones para los filtros seleccionados.</p>}</div>
        {selected && <SubscriptionDetail subscription={selected} customer={customers.get(selected.counterparty_id)} plan={plans.get(selected.plan_id)} payments={(data?.payments ?? []).filter((row) => row.subscription_id === selected.id)} events={(data?.events ?? []).filter((row) => row.subscription_id === selected.id)} alerts={(data?.alerts ?? []).filter((row) => row.subscription_id === selected.id)} canManage={canManage} canValidate={canValidate} busy={busy} onTransition={transition} onPayment={() => setShowPayment(true)} onValidate={(paymentId, validationStatus) => action({ action: "validate_payment", paymentId, validationStatus, reason: validationStatus === "rejected" ? "Rechazado en revisión de tesorería" : "Validado por tesorería" }, validationStatus === "validated" ? "Pago validado." : "Pago rechazado.")} onRenew={() => action({ action: "prepare_renewal", subscriptionId: selected.id }, "Renovación preparada y solicitud de cobro pendiente.")} />}
      </div>
    </section>
    {showSale && <SaleModal organizationId={organizationId!} plans={(data?.plans ?? []).filter((row) => row.is_active)} customers={data?.customers ?? []} onClose={() => setShowSale(false)} onSaved={async () => { setShowSale(false); setMessage("Venta creada; queda pendiente de pago y sin activar."); await load(); }} />}
    {showPayment && selected && <PaymentModal organizationId={organizationId!} subscription={selected} onClose={() => setShowPayment(false)} onSaved={async () => { setShowPayment(false); setMessage("Pago registrado en validación; el servicio aún no se activa."); await load(); }} />}
    {showPlans && <PlansModal organizationId={organizationId!} plans={data?.plans ?? []} onClose={() => setShowPlans(false)} onSaved={load} />}
  </div>;
}

function Kpi({ label, value, detail }: { label: string; value: string; detail: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }

function SubscriptionDetail({ subscription, customer, plan, payments, events, alerts, canManage, canValidate, busy, onTransition, onPayment, onValidate, onRenew }: { subscription: Subscription; customer?: Customer; plan?: Plan; payments: Payment[]; events: TimelineEvent[]; alerts: Alert[]; canManage: boolean; canValidate: boolean; busy: boolean; onTransition: (status: SubscriptionStatus) => void; onPayment: () => void; onValidate: (id: string, status: string) => void; onRenew: () => void }) {
  return <aside className="sv-detail"><div><span className="eyebrow">EXPEDIENTE</span><h3>{subscription.subscription_code}</h3><p>{customer?.trade_name || customer?.legal_name} · {plan?.name}</p></div><div className="sv-money-grid"><span>Venta contratada<strong>{money(subscription.gross_amount, subscription.currency_code)}</strong></span><span>Pago validado<strong>{money(subscription.validated_paid_amount, subscription.currency_code)}</strong></span><span>En validación<strong>{money(subscription.payment_validation_amount, subscription.currency_code)}</strong></span><span>Saldo pendiente<strong>{money(subscription.outstanding_amount, subscription.currency_code)}</strong></span></div><div className="sv-concepts"><span className={Number(subscription.validated_paid_amount) >= Number(subscription.gross_amount) ? "ok" : ""}>Pago validado</span><span className={subscription.status === "active" ? "ok" : ""}>Servicio activo</span><span>Ingreso devengado independiente</span></div><dl><div><dt>Vigencia</dt><dd>{displayDate(subscription.current_start_on)} → {displayDate(subscription.current_end_on)}</dd></div><div><dt>Cobranza</dt><dd>{subscription.billing_contact_email}</dd></div><div><dt>Operación</dt><dd>{subscription.operational_contact_email}</dd></div></dl>
    {canManage && <div className="sv-actions"><button className="primary-button" disabled={busy || ["cancelled", "voided"].includes(subscription.status)} onClick={onPayment}>Registrar pago</button>{allowedTransitions[subscription.status].map((status) => <button key={status} className="secondary-button" disabled={busy || (status === "active" && Number(subscription.validated_paid_amount) < Number(subscription.gross_amount))} onClick={() => onTransition(status)}>{status === "active" ? "Activar servicio" : statusLabels[status]}</button>)}{["active", "expiring", "expired_pending_payment", "suspended_nonpayment"].includes(subscription.status) && <button className="secondary-button" disabled={busy} onClick={onRenew}>Preparar renovación</button>}</div>}
    <h4>Pagos</h4><div className="sv-payment-list">{payments.length ? payments.map((payment) => <div key={payment.id}><span><strong>{money(payment.amount, payment.currency_code)}</strong><small>{payment.provider_code} · {displayDate(payment.paid_at)}</small></span><span className={`sv-payment-state is-${payment.validation_status}`}>{payment.validation_status === "pending" ? "En validación" : payment.validation_status === "validated" ? "Validado" : "Rechazado"}</span>{canValidate && payment.validation_status === "pending" && <span className="sv-inline-actions"><button onClick={() => onValidate(payment.id, "validated")}>Validar</button><button onClick={() => onValidate(payment.id, "rejected")}>Rechazar</button></span>}</div>) : <p>Sin pagos registrados.</p>}</div>
    <h4>Alertas abiertas</h4><div className="sv-alert-list">{alerts.filter((alert) => alert.status === "open").slice(0, 5).map((alert) => <div key={alert.id}><strong>{displayDate(alert.alert_on)} · {alert.priority}</strong><small>{alert.action_recommended}</small></div>)}</div>
    <h4>Línea de tiempo</h4><ol className="sv-timeline">{events.slice(0, 12).map((event) => <li key={event.id}><span /> <div><strong>{event.event_type.replaceAll("_", " ")}</strong><small>{displayDate(event.created_at)}{event.reason ? ` · ${event.reason}` : ""}</small></div></li>)}</ol>
  </aside>;
}

function SaleModal({ organizationId, plans, customers, onClose, onSaved }: { organizationId: string; plans: Plan[]; customers: Customer[]; onClose: () => void; onSaved: () => void }) {
  const [customerId, setCustomerId] = useState(customers[0]?.id ?? ""); const [planId, setPlanId] = useState(plans.find((plan) => !plan.is_exceptional)?.id ?? plans[0]?.id ?? ""); const [customerType, setCustomerType] = useState<"company" | "individual">("company"); const [startOn, setStartOn] = useState(today()); const [dueOn, setDueOn] = useState(today()); const [billingEmail, setBillingEmail] = useState(""); const [operationalEmail, setOperationalEmail] = useState(""); const [discount, setDiscount] = useState("0"); const [exceptionReason, setExceptionReason] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const customer = customers.find((row) => row.id === customerId); setBillingEmail(customer?.billing_email || customer?.email || ""); setOperationalEmail(customer?.email || ""); }, [customerId, customers]);
  const plan = plans.find((row) => row.id === planId);
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); setError(""); const response = await fetch("/api/virtual-secretary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "create_sale", organizationId, counterpartyId: customerId, planId, customerType, startOn, dueOn, billingEmail, operationalEmail, discountAmount: discount, automaticRenewal: true, saleOrigin: "Venta directa / CRM", exceptionReason }) }); const payload = await response.json().catch(() => null) as { error?: string } | null; if (response.ok) await onSaved(); else setError(payload?.error === "monthly_plan_requires_authorized_exception" ? "El plan mensual exige autorización y motivo." : "Revisa cliente, correos, precio y permisos."); setSaving(false); };
  return <div className="modal-backdrop"><section className="entry-modal sv-modal" role="dialog" aria-modal="true"><div className="modal-header"><div><span className="eyebrow">VENTA ANTICIPADA</span><h2>Nueva suscripción</h2><p>La venta quedará pendiente de pago; no activa el servicio.</p></div><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid"><label>Cliente<select required value={customerId} onChange={(event) => setCustomerId(event.target.value)}>{customers.map((row) => <option key={row.id} value={row.id}>{row.trade_name || row.legal_name}</option>)}</select></label><label>Tipo<select value={customerType} onChange={(event) => setCustomerType(event.target.value as "company" | "individual")}><option value="company">Empresa</option><option value="individual">Persona natural</option></select></label><label>Plan<select value={planId} onChange={(event) => setPlanId(event.target.value)}>{plans.map((row) => <option key={row.id} value={row.id}>{row.code} · {row.name}{row.is_exceptional ? " (excepcional)" : ""}</option>)}</select></label><label>Precio lista neto<input readOnly value={plan ? money(customerType === "company" ? plan.company_net_price : plan.individual_net_price, plan.currency_code) : ""} /></label><label>Inicio proyectado<input type="date" required value={startOn} onChange={(event) => setStartOn(event.target.value)} /></label><label>Vencimiento del cobro<input type="date" required value={dueOn} onChange={(event) => setDueOn(event.target.value)} /></label><label>Descuento autorizado<input type="number" min="0" step="1" value={discount} onChange={(event) => setDiscount(event.target.value)} /></label><label>Correo cobranza<input type="email" required value={billingEmail} onChange={(event) => setBillingEmail(event.target.value)} /></label><label>Correo operativo<input type="email" required value={operationalEmail} onChange={(event) => setOperationalEmail(event.target.value)} /></label>{plan?.is_exceptional && <label className="form-grid-wide">Motivo de excepción mensual<textarea required value={exceptionReason} onChange={(event) => setExceptionReason(event.target.value)} /></label>}</div>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? "Creando…" : "Confirmar venta y generar cobro"}</button></div></form></section></div>;
}

function PaymentModal({ organizationId, subscription, onClose, onSaved }: { organizationId: string; subscription: Subscription; onClose: () => void; onSaved: () => void }) {
  const [method, setMethod] = useState("bank_transfer"); const [provider, setProvider] = useState("transferencia_bancaria"); const [amount, setAmount] = useState(String(subscription.outstanding_amount)); const [reference, setReference] = useState(""); const [providerStatus, setProviderStatus] = useState(""); const [evidence, setEvidence] = useState<File | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const form = new FormData(); Object.entries({ organizationId, subscriptionId: subscription.id, paymentMethod: method, providerCode: provider, amount, currencyCode: subscription.currency_code, paidAt: new Date().toISOString(), idempotencyKey: crypto.randomUUID(), transferReference: reference, externalTransactionId: method === "gateway" ? reference : "", providerStatus }).forEach(([key, value]) => form.set(key, value)); if (evidence) form.set("evidence", evidence); const response = await fetch("/api/virtual-secretary", { method: "POST", body: form }); const payload = await response.json().catch(() => null) as { error?: string } | null; if (response.ok) await onSaved(); else setError(payload?.error === "duplicate_payment" ? "El proveedor ya informó este pago." : "No fue posible registrar el pago; revisa evidencia, monto y referencia."); setSaving(false); };
  return <div className="modal-backdrop"><section className="entry-modal sv-modal" role="dialog" aria-modal="true"><div className="modal-header"><div><span className="eyebrow">COBRO · {subscription.subscription_code}</span><h2>Registrar pago</h2><p>Quedará en validación hasta confirmación de tesorería o conciliación.</p></div><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid"><label>Medio<select value={method} onChange={(event) => { setMethod(event.target.value); setProvider(event.target.value === "gateway" ? "webpay" : "transferencia_bancaria"); }}><option value="bank_transfer">Transferencia bancaria</option><option value="gateway">Pasarela</option></select></label><label>Proveedor / adaptador<input required value={provider} onChange={(event) => setProvider(event.target.value)} placeholder="webpay, mercado_pago…" /></label><label>Monto<input type="number" min="1" required value={amount} onChange={(event) => setAmount(event.target.value)} /></label><label>Moneda<input readOnly value={subscription.currency_code} /></label><label>Referencia externa<input required value={reference} onChange={(event) => setReference(event.target.value)} /></label>{method === "gateway" && <label>Estado informado por proveedor<input required value={providerStatus} onChange={(event) => setProviderStatus(event.target.value)} placeholder="AUTHORIZED" /></label>}<label>Evidencia {method === "bank_transfer" ? "*" : ""}<input type="file" required={method === "bank_transfer"} accept="application/pdf,image/jpeg,image/png" onChange={(event) => setEvidence(event.target.files?.[0] ?? null)} /></label></div>{error && <p className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving ? "Registrando…" : "Registrar en validación"}</button></div></form></section></div>;
}

function PlansModal({ organizationId, plans, onClose, onSaved }: { organizationId: string; plans: Plan[]; onClose: () => void; onSaved: () => void }) {
  const [drafts, setDrafts] = useState(plans.map((plan) => ({ ...plan, individual_net_price: String(plan.individual_net_price), company_net_price: String(plan.company_net_price) }))); const [busy, setBusy] = useState("");
  const save = async (plan: typeof drafts[number]) => { setBusy(plan.id); const response = await fetch("/api/virtual-secretary", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "update_plan", organizationId, planId: plan.id, individualPrice: plan.individual_net_price, companyPrice: plan.company_net_price, isActive: plan.is_active }) }); if (response.ok) await onSaved(); setBusy(""); };
  return <div className="modal-backdrop"><section className="entry-modal sv-modal sv-plans-modal"><div className="modal-header"><div><span className="eyebrow">CATÁLOGO GEIMSER</span><h2>Planes y precios</h2><p>Desactivar conserva todo el historial.</p></div><button className="close-button" onClick={onClose}>×</button></div><div className="sv-plan-list">{drafts.map((plan, index) => <div key={plan.id}><strong>{plan.code} · {plan.name}</strong><label>Persona natural<input type="number" min="0" value={plan.individual_net_price} onChange={(event) => setDrafts((rows) => rows.map((row, position) => position === index ? { ...row, individual_net_price: event.target.value } : row))} /></label><label>Empresa<input type="number" min="0" value={plan.company_net_price} onChange={(event) => setDrafts((rows) => rows.map((row, position) => position === index ? { ...row, company_net_price: event.target.value } : row))} /></label><label className="sv-check"><input type="checkbox" checked={plan.is_active} onChange={(event) => setDrafts((rows) => rows.map((row, position) => position === index ? { ...row, is_active: event.target.checked } : row))} /> Activo</label><button className="secondary-button" disabled={busy === plan.id} onClick={() => void save(plan)}>Guardar</button></div>)}</div></section></div>;
}
