create index if not exists public_market_tenders_opportunity_idx on public.public_market_tenders (opportunity_id) where opportunity_id is not null;
create index if not exists public_market_documents_tender_org_fk_idx on public.public_market_documents (tender_id, organization_id);
create index if not exists public_market_awards_tender_org_fk_idx on public.public_market_award_history (tender_id, organization_id);

drop policy if exists "operators manage public market radar settings" on public.public_market_radar_settings;
drop policy if exists "operators manage public market tenders" on public.public_market_tenders;
drop policy if exists "operators manage public market documents" on public.public_market_documents;
drop policy if exists "operators manage public market award history" on public.public_market_award_history;
drop policy if exists "operators insert public market radar settings" on public.public_market_radar_settings;
drop policy if exists "operators update public market radar settings" on public.public_market_radar_settings;
drop policy if exists "operators delete public market radar settings" on public.public_market_radar_settings;
drop policy if exists "operators insert public market tenders" on public.public_market_tenders;
drop policy if exists "operators update public market tenders" on public.public_market_tenders;
drop policy if exists "operators delete public market tenders" on public.public_market_tenders;
drop policy if exists "operators insert public market documents" on public.public_market_documents;
drop policy if exists "operators update public market documents" on public.public_market_documents;
drop policy if exists "operators delete public market documents" on public.public_market_documents;
drop policy if exists "operators insert public market award history" on public.public_market_award_history;
drop policy if exists "operators update public market award history" on public.public_market_award_history;
drop policy if exists "operators delete public market award history" on public.public_market_award_history;

create policy "operators insert public market radar settings" on public.public_market_radar_settings for insert to authenticated with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_radar_settings.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators update public market radar settings" on public.public_market_radar_settings for update to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_radar_settings.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations'))) with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_radar_settings.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators delete public market radar settings" on public.public_market_radar_settings for delete to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_radar_settings.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));

create policy "operators insert public market tenders" on public.public_market_tenders for insert to authenticated with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_tenders.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators update public market tenders" on public.public_market_tenders for update to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_tenders.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations'))) with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_tenders.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators delete public market tenders" on public.public_market_tenders for delete to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_tenders.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));

create policy "operators insert public market documents" on public.public_market_documents for insert to authenticated with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_documents.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators update public market documents" on public.public_market_documents for update to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_documents.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations'))) with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_documents.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators delete public market documents" on public.public_market_documents for delete to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_documents.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));

create policy "operators insert public market award history" on public.public_market_award_history for insert to authenticated with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_award_history.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators update public market award history" on public.public_market_award_history for update to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_award_history.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations'))) with check (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_award_history.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
create policy "operators delete public market award history" on public.public_market_award_history for delete to authenticated using (exists (select 1 from public.organization_memberships membership where membership.organization_id = public_market_award_history.organization_id and membership.user_id = (select auth.uid()) and membership.role in ('administrator', 'finance', 'operations')));
